# Native Windows build (MSYS2 MinGW-w64), as opposed to the Linux → Windows
# cross build that cmake/toolchain-mingw64.cmake describes.
#
# Two things the cross build gets for free have to be arranged here:
#
# 1. -UWIN32. The toolchain file removes it for the cross build; see the
#    comment there. MinGW defines it on a native host too.
#
# 2. <GL/gl.h> and <GL/glext.h>. On a case-insensitive filesystem both names
#    resolve to project headers before the system ones: include/gl/glext.h
#    (the decomp's cut-down copy for the original Win32 renderer, used only by
#    src/sysCore/oglGraphics.cpp, which is not built) and pc_port/gl/gl.h (the
#    port's wrapper that game code reaches as <gl/gl.h>). pc_port/gl/pc_opengl.h
#    then includes itself instead of OpenGL. Forwarding headers placed ahead of
#    every project include directory sort it out. Since case can't tell
#    <gl/gl.h> (game code, which wants the port wrapper) from <GL/gl.h>
#    (pc_opengl.h, which wants the system file), the gl.h forwarder uses
#    pc_opengl.h's include guard to tell the two apart.

if (NOT (WIN32 AND CMAKE_HOST_WIN32))
    return()
endif()

add_compile_options(-UWIN32)

find_path(PIKMIN_SYSTEM_GL_INCLUDE_DIR NAMES GL/glext.h REQUIRED)
set(_gl_shim_dir "${CMAKE_BINARY_DIR}/windows-native-shim")
file(WRITE "${_gl_shim_dir}/GL/gl.h"
    "/* Generated by cmake/windows-native.cmake. */\n"
    "#ifndef PIKMIN_PC_OPENGL_H\n"
    "#include \"${CMAKE_CURRENT_SOURCE_DIR}/pc_port/gl/pc_opengl.h\"\n"
    "#else\n"
    "#include \"${PIKMIN_SYSTEM_GL_INCLUDE_DIR}/GL/gl.h\"\n"
    "#endif\n")
file(WRITE "${_gl_shim_dir}/GL/glext.h"
    "/* Generated by cmake/windows-native.cmake. */\n"
    "#include \"${PIKMIN_SYSTEM_GL_INCLUDE_DIR}/GL/glext.h\"\n")
include_directories(BEFORE "${_gl_shim_dir}")

message(STATUS "Windows native build: GL/glext.h from ${PIKMIN_SYSTEM_GL_INCLUDE_DIR}")
